### ISSUE TITLE
Implement service to load user permissions from Database

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#101]
Need to create service and dao classes in order to support authorization mechanism in project.

Idea is for each user to load roles and permissions from Database.

Need to create query to load user's roles and for each role to load user permissions. Service class that will be create, will accept user email and  need to return DTO object that will contain the following informations , user email, user name, list of roles that are assign to user and list of permissions.

JSON structure that DTO object should return is following:
{
	"name": "Marin"
  	"surname": "Trpenovski"
  	"email":"marin.trpenovski@gmail.com"
  	"roles":[
	  {
	  	"name":"user"
		"permissions": [
			'Edit Faculty', 'View Faculty'
		]
	  }
	.
	.
	.
	]
}

**Comment by AngelaM123** [comment]
Created service and dao classes in order to support authorization mechanism , also created query to load user's roles and for each role to load user permissions

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. SQL is good, code is good as well. Good job.
