### ISSUE TITLE
Create REST endpoint to load user permissions

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#102]
Need to create REST endpoint that will return user permissions for user that sent request.

REST endpoint don't need to accept any query parameter or path variable and should return LIST of all permissions. 
User email that will be needed to load user permissions is available in JWT token and it's available in Spring Security Context.
Use this link as reference how to  get user from Security Contexts.
https://www.springcloud.io/post/2022-02/spring-security-get-current-user/#gsc.tab=0

**Comment by AngelaM123** [comment]
Created a REST endpoint that return user permissions for user that sent request. Also saw the suggested link from the above comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good, closing this issue now. 

 Solution is really good in terms of performance by avoiding create new query to load user permissions. Good job.
