### ISSUE TITLE
Implement validation rules for endpoints

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#11]
On service layer in each of the entities apply validation rules about properties of the object that is passed to REST endpoint.
Validation rules should follow definition of columns in DB if some column is mandatory then must have value for that property in model class also properties that are string can not be empty strings. Should prevent DB from it.

If some of the properties are not valid then:
1. Create new Exception (custom) that will accept message as parameter in constructor. (https://www.javatpoint.com/custom-exception)
2. In case some of the rules are not applied then throw newly created Exception and set message property to explain why this Exception occur.
3. Prevent REST service execution to reach DAO layer so will prevent to occur DB exception and to have dirty data in DB.

@AngelaM123 Please take a look at this issue . 

Estimate date: Wednesday 08.02.2023

**Comment by AngelaM123** [comment]
implemented validation rules for endpoints ,created custom Exception class

**Comment by MarinTrpenovski** [comment]
Code looks good @AngelaM123 

Implement following notes so we can close this issue.

![image](https://user-images.githubusercontent.com/27773018/217622515-fc834d69-af77-44b2-b440-42f0404e0da2.png)
Name of Exception to be more descriptive , like what is the purpose of that Exception? CustomException was just like example to create your own Exception. Name can be something like InvalidFieldsException or ValidationsException 

Also remove empty lines in CustomException constructor.
Leave empty space at begin of the class when define variable message in exception class

**Comment by AngelaM123** [comment]
made the corrections that were required applied all the classes that got changed

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good; Closing this issue.
