### ISSUE TITLE
Design Authorization logic in platform

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#116]
The idea is to think about the authorization schema that needs to be implemented in the project. 

Need to create roles with different sets of permissions so new users that will be added to the system to be linked to appropriate roles. 

Platfrom will need to have one more "module" which will be admin panel , where administrator can added new users/permissions/roles and tied them via UI , instead of creating and linking them directly via DB.

When you are done with defining schema for roles/permissions needs to authorize endpoints with appropriate permission in each of the REST endpoints in the application. 

@AngelaM123 You can start work on this issue.

**Comment by AngelaM123** [comment]
Implemented rest-endpoint in UserController class with mapping edit, with the purpose of adding role for any user. The endpoint receives two parameters - integers from the frontend, user_id and role_id. Then we insert these values into the many to many table in DB user_role_relation. I have already defined values for the role_permission_relation table, so any given role is already defined which permissions it supposed to has. I have tested the endpoint in postman with an existing user in DB, with previously logged in another user as admin, and previously inserted the new role of the existing user

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good for linking user to role. Fix following notes in order to completed this task.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/ddac0fa9-26f2-42f8-9109-e6dce42a5afb)
Message in Exception can be more descriptive like , explain which parameter is missing , not enough parameters doesn't explain to the users(and to developers when need to fix bug related with this code ) what is the problem. 


Other part of this issue is also implementing authorization check in the REST endpoints based on schema that you created. Need to use this annotations I think we explain it. 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/bdaa47fa-76fd-4451-9303-a46d4b555eeb)


IN DAO class method setUserRole need to refactor logic for SQL query because I think this code doesn't prevent SQL injection attacks. 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/53fcf2a2-dee2-4f9b-ad03-9a6d296e2aa8)

Use following link as reference for SQL injections to understand what they are and how to prevent them in java https://www.digitalocean.com/community/tutorials/sql-injection-in-java

**Comment by AngelaM123** [comment]
Applied the notes that were required in the previous comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good, closing this issue now
