### ISSUE TITLE
Implement Transaction annotation in application.

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#13]
Read following link about @Transaction annotation in spring. (https://vladmihalcea.com/spring-transactional-annotation/) 

When you finish with read and understand , integrate annotation in appropriate places in the application in each entity and when you are done write comment why this annotation is used and everything that you will learn about it.

 @AngelaM123 Please take a look at this issue. 

Estimate date: Thursday 09.02.2023

**Comment by AngelaM123** [comment]
I applied the required annotation on the places I thought we should use it, and down is the explanation on how I understand the work of this annotation.

We use this annotation to have data integrity, if during execution we encounter an error, it returns to its original position and that means the queries are not committed to the database (as an example we can use git). With the help of this annotation JDBC in the background checks if the query is valid. It is used every time we have 2 queries. It is important to mention rollback, which means that if one query passes the other one fails, the annotation itself does a rollback and returns to its original state. This annotation is always placed on queries that do manipulation with data such as save, update and delete. It is also important to say that we place this annotation in the service layer  if we want to change the domain model for client  where we have to provide the same data in a different model, we can change the domain model without impacting the DAO layer by providing a different service or by creating a interface and implementing the interface in different model and with the same service populate the model based on the client.

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good; Closing this issue
