### ISSUE TITLE
Create REST endpoint

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#18]
Need to create REST endpoint for each of the entities that will return Map. 
This REST endpoint will accept GET method and will return Map of appropriate entity where key is id and value is appropriate object for that id. 

Follow layered approach , means for each of the entities need to create methods in appropriate packages (controller/service/dao).

Estimation : 13.02.2023 Monday

**Comment by AngelaM123** [comment]
Created REST endpoint for each of the entities that are returning Map also followed the layered approach ,meaning created all methods that are needed in the controller/service/dao layer

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good; Closing this issue.
