### ISSUE TITLE
REST endpoint for multiple column

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#19]
Need to create REST endpoints that will return JSON structure for following data:

Each of Endpoints should accept id as query parameter. Should have validation to check does query param is passed and if not to throw Exception with appropriate message.

First endpoint should accept id of University and return name of university, number of faculties from that university and all faculties.
Second endpoint should accept id of Faculty and return name of faculty and number of all subjects and list of all subjects from that faculty.
Third endpoint should accept student id and should return name of Student and number of subjects that student have and list of all Subject that belong to that student.

Use layered approach, means to create methods in each of the appropriate packages (controlller/services/dao) for each of the endpoints. 

You can use DTO. Test endpoints that you will create with postman before completed this issue. 

Estimation 15.02.2023 Wednesday

**Comment by AngelaM123** [comment]
Created REST endpoints for multiple columns made DTO classes used layer approach

**Comment by MarinTrpenovski** [comment]
Code looks good; Closing this issue @AngelaM123
