### ISSUE TITLE
Complex update operation

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#20]
Create new REST endpoint that will update two tables.

Rest endpoint should accept Student and Subject objects and update appropriate records in DB. Need to use DTO object.
Also need to apply validation rules (like mandatory fields)  before execute update action.

Estimation: 16.2.2023 @AngelaM123

**Comment by AngelaM123** [comment]
Created REST endpoint that is updating two tables ,used DTO and validation rules

**Comment by MarinTrpenovski** [comment]
Code looks good; closing this issue @AngelaM123
