### ISSUE TITLE
Test newly created REST endpoints

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#36]
All REST endpoints that were created need to be tested via POSTMAN.

Install Postman locally.

Each of the endpoints test it using postman. Try different scenarios for REST endpoints in order to cover more edge cases. 

Scenarios, like pass different query parameters to search REST endpoint for each of the entities. Try to use search API without any query parameters.

Try to update/save new entity in DB and data that will be passed as body from POSTMAN set to missed some of mandatory fields.

If there are other cases that you might cover during testing with postman test them as well. 

In comment when you are done write each of the REST endpoints that you test it. And cases that you have covered.

Estimation date: 20.02.2023 Monday 

@AngelaM123 You can start work on this issue when issues #19  and #20 are done.

**Comment by AngelaM123** [comment]
These are the following scenarios for testing the REST endpoints for the University API /api/<entity> :
/save - by using the POST method in postman I am creating new object of <entity> in the database
The parameter id is not required but all the other parameters have to have values(strings with one or more characters) or there will be exception message 
/update - by using PUT method in postman I can update the new object in the database 
The value of parameter id has to be present if not there is an exception message for error.
/{id} - by using DELETE method in postman I am deleting an object form database with a given id 
By using the GET  method in postman I can test the following REST endpoints :
 /all - I get a JSON array object of <entity> JSON objects
/map - I get a JSON map object of pairs composed of integer id and an JSON object <entity> 
/search - I get a JSON array object of <entity> JSON objects which have the same given attributes  
I can test the search endpoint with multiple parameters - attributes and can also leave out some values of the attributes ,but there has to be at least one parameter value present, if all the parameters are null or empty strings (between 1 and 45 characters )we get an exception message for error 
/{id} - I get an JSON object with a given id
This endpoint its concrete example from university entity and its an example where an entity object contains list of objects
/faculties/{id} - I get a JSON array object of faculty JSON objects which have the same university id 
In every entity I have the same example with different combinations
