### ISSUE TITLE
General Exception Handler

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#37]
Implement General Exception Handler in Application.
This handler will contain all Exceptions that might occur during execution of program.

So for each of the Exception , define different type of Response that will be returned to the Client(UI/POSTMAN) in json format. 
Example : if Invalid search parameter exception occur , you should set what will be status code that will be returned from server and also can set message that will be passed to the user as part of JSON response. 

Use this links (https://www.tutorialspoint.com/spring_boot/spring_boot_exception_handling.htm  https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc)

When you are done with implementation try to test some of Exceptions with Postman. In comment describe scenario that you have tested. 

If you have any questions related with issue, feel free to ask me @AngelaM123 

Estimation :  21.02.2023

**Comment by AngelaM123** [comment]
Created the General Exception Handler ,used the links that were suggested .After finishing the implementation tested few examples.
One scenario that I tested with Postman was for university/search ,an GET method where I didn't put value on any parameter ,and it is a must to have at least for one parameter value ,so while testing with no value defined for any parameter I got a message (Error occurred: not enough query parameters) and it means that it was thrown QueryException

**Comment by MarinTrpenovski** [comment]
I think in General Exception class missed to be catch general Exception if occur. 
Please add this case in the class.
Otherwise code looks good @AngelaM123

**Comment by AngelaM123** [comment]
General Exception is added in the code

**Comment by MarinTrpenovski** [comment]
Code looks good; Closing this issue @AngelaM123
