### ISSUE TITLE
REST services for modify subjects assigned to students

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#43]
Create REST endpoints that will create student in DB and will create subjects in DB. REST endpoint accept DTO object as Request body and should provide appropriate validation rules , first to check does student object and subjects list are defined in the DTO and does each of the object properties pass validation rules that are already applied.
If doesn't pass to throw ValidationException with appropriate message.

Also need to create relation between newly created subject and subjects.

Follow layered architecture approach. (controller, service, dao).

Estimation date: 22.02.2023 Wednesday.

**Comment by AngelaM123** [comment]
Created REST endpoint that creates student and subjects in DB ,made proper DTO class, created relation between student and subjects also followed the layer approach

**Comment by MarinTrpenovski** [comment]
Code looks good, solution is also good. 

Few comments from my side :

1. In StudentController class in validation check for subjects, need also to see does list is initialize before check does size is bigger then zero.
2. In saveStudentSubjectsIds method add "tab" space when start new line. 
3. In StudentDAOImpl class in method saveStudentSubjectsIds have redundant initialization of some of the variables which can be removed. Please clean it.

Idea to improve the implementation. 
With this approach you have 2 for loops for iteration over subjects list one in service and other in dao classes.
You can change implementation of method which save relation between subject and student and instead of taking array of subjectIds can pass only subjectId. Subject ID you already have in service method after saving subject in DB in the for loop , so for each subject get ID , studentId you already have and pass this IDs to the method in DAO class. This should be done for each subject from list. I think by this approach one for loop can be removed and performance can be improved. 

@AngelaM123 What you think about this solution ?

**Comment by AngelaM123** [comment]
Made implementation for the comments that are above also tried to implement the suggested idea to improve the code

**Comment by MarinTrpenovski** [comment]
@AngelaM123 What will happened if I pass DTO to REST service where student object is set but subjects list is not set ?

In SubjectServiceImpl in saveStudentSubjects method have redundant code, also in subjectDAO please add more descriptive name of saveDTO method I think it will be better to be saveReturnId what you think ? or just left to be save and  return type of method (Integer) can be enough to understand that return new generated ID. 
In DAO Impl classes (StudentDAO and SubjectDAO)  in some methods there is also redundant code please remove it.

**Comment by AngelaM123** [comment]
Manage to rename the saveDTO method, also removed the redundant code in the mentioned classes in the previous comment ,added condition in the appropriate place

**Comment by MarinTrpenovski** [comment]
Code looks good @AngelaM123 Closing this issue.
