### ISSUE TITLE
Add service for creating new university

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#44]
Need to create REST endpoint that will create new University and create Faculties (at least one Faculty but could be multiple) that are tied to that University.

REST endpoint takes one object as Request Body, should validate that objects exist in the body if objects doesn't exist need to throw Exception for invalid Parameters.

Also should validate properties for each of the objects before try to save them in DB. If some of the fields are not valid to throw appropriate Exception.

Follow layered architecture approach. 

Estimation: Thursday 23.02.2023

**Comment by AngelaM123** [comment]
I have created REST endpoint for creating new university ,followed layered approach

**Comment by MarinTrpenovski** [comment]
@AngelaM123 what will happened if UniversityFacultiesDTO set University object but doesn't set Faculty list and pass that DTO to REST API ?

Why do you have 2 same methods in facultyDAO , save and saveDTO, what is difference ? I think save method can be used to save faculty in DB. What you think  ? Is there are other reason why both methods exists ?

In UniversityFacultiesDTO class encapsulation for some of the properties is not applied. Please check that and fix.

**Comment by AngelaM123** [comment]
Modified the condition in the controller for empty list, renamed the saveDTO method to saveReturnId and modified the save method.
Modified UniversityFacultiesDTO

**Comment by MarinTrpenovski** [comment]
@AngelaM123 in UniversityFacultiesDTO I think encapsulation is not applied yet. Please take a look again.
![image](https://user-images.githubusercontent.com/27773018/222358751-51c2d766-8b16-45e9-96bf-9b95dd348d5b.png)

**Comment by AngelaM123** [comment]
Encapsulation is applied now

**Comment by MarinTrpenovski** [comment]
Code looks good now. Closing this issue @AngelaM123
