### ISSUE TITLE
Delete student from DB

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#45]
Need to create REST endpoint that will accept studentId and subject(s) id as query parameters (subject Ids can be multiple subject ids like subjecIds=43,56.45) which will delete appropriate student and subject by using parameters that are passed.

REST endpoint should validate does parameters are valid parameters (Number for students and array of numbers for subjects ids).

Need to check does each of the subject is tied to any other Student. 
If subject is tied to any other student need to delete only relation between student and subject otherwise if subject is not tied to any other student then delete relation between student and subject and delete subject too.

Use layered architecture. 

Test REST endpoints using Postman. Try different scenarios.

Estimation date:  24.02.2023 Friday

**Comment by AngelaM123** [comment]
Manage to create REST endpoint that accept studentId and subject(s) id as query parameters which will delete appropriate  student and subject by using parameters that are passed, made proper check does each of the subject is tied to any other Student and deleted only the relation or whole subject depending on the situation , used layered architecture.
Tested in Postman more than one scenario

**Comment by MarinTrpenovski** [comment]
Code and implementation looks good. I have some notes:

![image](https://user-images.githubusercontent.com/27773018/222359221-51c42779-476b-43af-8617-ae6ee30fdfe6.png)
Method in service layered missing something. What will happened if one of the query for delete pass and other one fail ?

In SubjectDAOImpl class in getSubjectsStudent method query can be modified. 
![image](https://user-images.githubusercontent.com/27773018/222361122-b39562bf-c2c1-4059-beef-03d7971c2307.png)
Instead of return all rows you can use count operation and query will return exact number of rows that match condition. After that while loop will not be needed. Directly can access to value of count via code and skip this loop. What you think about this @AngelaM123  ?

DeleteDTO method in SubjectDaoImpl class can be more descriptive. Please rename it. Can be something like removeSubStRel. 
![image](https://user-images.githubusercontent.com/27773018/222361790-1fc01ec6-960d-4af5-85bc-e79bf6cd4284.png)
What you think about this ?

In StudentServiceImpl in deleteStudentSubjects method please clean up code. Remove println statements and commented code. 
![image](https://user-images.githubusercontent.com/27773018/222362860-12ee9acf-636c-461a-8b7b-66045edabdc8.png)


@AngelaM123 Please apply following notes so we can close this issue.

**Comment by AngelaM123** [comment]
Did corrections in the service layer for the method deleteStudentSubjects 
Changed the sql query added COUNT instead of  *  and with that removed the while loop because now in not needed
Renamed the deleteDTO method  in SubjectDaoImpl class and made more descriptive name as suggested 
Deleted the comments In StudentServiceImpl in deleteStudentSubjects method  and removed the println statements

**Comment by MarinTrpenovski** [comment]
IN service layer in method deleteStudentSubjects  I think corrections are not applied 
![image](https://user-images.githubusercontent.com/27773018/222721228-7ab875e5-629b-4c37-b66c-1205319e3121.png)
What you think @AngelaM123 
In DAO class in some of methods have redundant code. PLease remove it. We don't need it, right.
![image](https://user-images.githubusercontent.com/27773018/222721436-84575f19-7194-4ee4-ab2a-8625b7450f55.png)

**Comment by AngelaM123** [comment]
Made proper corrections in the code and made PR

**Comment by MarinTrpenovski** [comment]
Code looks good now, closing this issue @AngelaM123
