### ISSUE TITLE
Create profiles(environments) in spring

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#46]
Create two profiles in spring. One is for local development other is for development environment . Read this link how to create profiles in spring https://mkyong.com/spring-boot/spring-boot-profile-based-properties-and-yaml-example/ 

In property file should have two different entries; like external.services="This are services from local properties" and external.services="This are services from dev properties"

Explain why we need profiles in spring and how to load specific properties file and use values from that file with maven.

Estimation time : 27.02.2023 (Monday)

**Comment by AngelaM123** [comment]
Without using spring profiles it can be really challenging to manage environment specific configurations, Spring Profiles helps us to set right configurations on right environments very easy ,or with other words we can customize a build for different environments.
The way i understand it with example is that we have 3 different enivronments local,dev and production in every case i choose one of them and for each of them for  take the appropriate credentials.Example if i have string external service and i want to put it on dev it take the dev property file and will point at the another dev service , i am having a flag just to separate them so i can use them for different kind of versions
When I use this line in terminal  mvn clean install -D spring.profiles.active=dev we are activating the profile
