### ISSUE TITLE
Some GET REST service

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#47]
Create REST endpoint that will return following data:

1. Create GET endpoint (accept studentId as path variable)  that will return Student name and index and Subject name and subject credits that have odd number of indeks and sum of credits for subjects that student have is add number. If doesn't exit such record in DB will need to return message that doesn't have that record . 

For the endpoint implement validation rules,  does appropriate and valid parameters are sent to the REST endpoint. 

Estimation date: 28.02.2023 Tuesday

**Comment by AngelaM123** [comment]
Manage to create GET endpoint that returns Student name and index and Subject name and subject credits that have odd number of indeks and sum of credits for subjects that student have is odd number and also if there is no such record in DB is returning message that doesn't have that record

**Comment by MarinTrpenovski** [comment]
I think that else condition doesn't need in REST controller. What you think @AngelaM123 Can you explain what will happened if we remove else statement in the code. 
I think println statement doesn't have any business value , so can be removed. What you think ? We don't need to println if doesn't found any subject with that criteria, we need to return message as json response from REST service. End users doesn't see what will be printed in console, right ?
![image](https://user-images.githubusercontent.com/27773018/222722339-40e7cf75-304d-410c-993c-94a3e6682736.png)
Also in following method I think we don't need else condition. What you think ?
![image](https://user-images.githubusercontent.com/27773018/222722804-0a1ce188-5777-41e9-97ae-20c333a6ed05.png)

Please check on other places if have similar scenarios like this with else statements and fix them. 

![image](https://user-images.githubusercontent.com/27773018/222723228-50195c0b-30c3-4a56-ae17-d433103b971d.png)
This method is defined in interface missing something in implementation. What you think ?

![image](https://user-images.githubusercontent.com/27773018/222723534-8c2022df-7da2-4872-960b-3d00d6df3e0f.png)
I think println statement  in DAO class doesn't have any business value and can be removed. What you think ?


![image](https://user-images.githubusercontent.com/27773018/222723922-329ca158-4b5a-4279-9e09-141d1acc8533.png)
In StudentDAO class in method saveStudentSubjectsIds I think sql String can be declared and initialize in one line; doesn't need first to declare and after that to initialize.

**Comment by AngelaM123** [comment]
Made the required corrections and applied the suggestions

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good; Closing this issue.
