### ISSUE TITLE
Research about JWT and Basic Authentication in Web application

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#75]
Need to understand what is JWT token Authentication in Web applications .  
How is Spring generate JWT , what is encryption and what is decryption of token
What is JWT token ? 
What information keep in JWT token 
Use this link as reference for JWT Token https://jwt.io/

**Comment by AngelaM123** [comment]
JSON Web Token is an open industry standard used to share information between two entities, usually a client and a server. They contain JSON objects which have the information that needs to be shared. The token is usually generated in the server and sent to the client where it is stored in the session storage or local storage. To access a protected resource the client would send the JWT in the header.
Encryption is a reversible process that can be decrypted back to the original data using a secret key or algorithm. It generates token value randomly for plaintext and stores mapping in database, it converts plain text into the coded one that appears to be meaningless while decryption is the process that converts ciphertext into plaintext.

**Comment by MarinTrpenovski** [comment]
Explanation looks good @AngelaM123 Closing this issue now.
