### ISSUE TITLE
Configure Filter define in Project

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#77]
In project Filter is already created.
Need to configure a filter so some of the requests not be intercepted because the idea of the filter is to Check does request have valid token.
But endpoints like  /login and /signup doesn't have token in header because users still don't have JWT token generated for them.

Try to add new filter . Idea is to have two filters in the project one that will intercept request that need to be authenticated (Check does token is valid) and other one will intercept requests which doesn't have JWT token in header (user is not authenticated yet).

Use this link as reference how to define multiple filters in application. https://www.tutorialspoint.com/how-do-you-define-multiple-filters-in-jsp

**Comment by AngelaM123** [comment]
Applied new  required filter , used the suggested link from the above comment

**Comment by MarinTrpenovski** [comment]
Adding new filter in application is correct. But both filters are triggered on same URL.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/528652fd-08aa-4700-992d-9bcd71eb041a)
Both filter are applied on same URL.
See description of issue 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/e2049aee-f39f-4b9b-9950-a87ba1100cbf)

Change path in both of the filters example one to point to /api other to be /auth. 
In both filters add system out println statement that filter was triggered to be printed in console and from postman fire request that will trigger one filter then other request that will trigger other request. This is for testing purposes. 
@AngelaM123 you can apply this notes.

**Comment by AngelaM123** [comment]
Applied the required changes , changed the path for both filters , added system out println statement for testing purposes

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good closing this issue now.
