### ISSUE TITLE
Implement sign up functionality in backend services

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#78]
Need to create new REST endpoint that will create add new users in System (Database). 
Need to have service and dao layer methods for this.
Also need to create new User model class.
Password should be encrypted when is saved in Database. Use this video as reference https://www.youtube.com/watch?v=lB6pNVmrCTs

Apply validation checks each of the User model properties has values. (Not Null check or empty string) 
Also need to check does user already exist (Check by email address)

**Comment by AngelaM123** [comment]
Created new REST endpoint and also created add users in System, made the dao ,service layer and model class for User. Password is encrypted when it is saved in Database and validation check is applied,
Used this link as help to solve a part of this task https://www.baeldung.com/spring-security-registration-password-encoding-bcrypt

**Comment by MarinTrpenovski** [comment]
Code looks good. Please fix following notes. @AngelaM123 PLease fix following notes:
1. Structure code well in User Controller
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/483af14f-caa6-43bf-bc44-897446eba6cd)

**Why do we need /check REST endpoint in User controller ? I think can be removed this REST endpoint. ONly need service because we user service when /save user to check does user exist in DB , right ? I think can be removed this endpoint**

2. How you get idea for method name "deleteCountry" ?
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/46dbe565-b705-44d9-bacf-f1b190a2b050)
3.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/4925ca61-c2ad-4af2-a0df-a825f9c74f62)
Structure code well
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/639b4cfb-47f6-44ea-b157-c86619d7c17d)
. Typo issue in getById method in user controller
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/622e1b3c-8ec8-46cc-8c67-e9a068d771df)

In UserDAO structure code better
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/429b61c5-cdd0-48f1-af66-ec038f94092c)

![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/c83a4786-bed6-495e-bfd5-fe46ddfa77b2)

in User service in update method structure code better, same is for save method
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/e1d0dd29-0e78-4135-8e7a-6258b7f62a74)

**Comment by AngelaM123** [comment]
I have read and applied all notes that were suggested in the above comment including the code structure , renaming the method ,removing all empty lines in each class

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good but fix following note in order to close this issue.

In User controller throws declaration should be in same line as method definition. Its more readable.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/e02dbbec-6601-4cb6-bd35-5e189691d0b2)

**Comment by AngelaM123** [comment]
Made the required correction in the User controller class

**Comment by MarinTrpenovski** [comment]
Code looks good @AngelaM123 Closing this issue.
