### ISSUE TITLE
Implement Spring security in project

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#79]
Need to add dependency spring security in project via pom file. When dependency is added need to configure Spring security to allow each of the request to able to access to appropriate endpoint.
At beginning actually need to add security as module in project but to disable it.

Use this link as reference how to disable security in spring https://howtodoinjava.com/spring-security/disable-security-configuration/

**Comment by AngelaM123** [comment]
Dependency that was needed was added via pom file , disabled the security , used the suggested link above

**Comment by MarinTrpenovski** [comment]
Implementation looks good. Please fix styling note for AuthSecurity: "Remove empty space when declare class"
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/b5e52c7d-6868-4f32-95d9-b3c963bbba41)


One more note, I notice that you have disabled security in both ways, via proprery file (application.properties) and via configuration class (AuthSecurity) no need to disabled it in both ways. 
You can remove one approach. My suggestion is to remove disabled security from application(s).properties files.
Via configuration class you have bigger control over security and can modify security in project more easily in future.
@AngelaM123 Please apply following notes in order to close this issue.

**Comment by AngelaM123** [comment]
Applied the required notes from the above comment including the styling and removing one of the approaches the one from the property files

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good closing this issue.
