### ISSUE TITLE
Implement login functionality in backend services

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#80]
Need to have new rest endpoint for login purposes. 
Endpoint should accept query parameters userId(email address) and password(string).
Need to check does user exist in Database and if user exist need to check does password passed as query parameter is same as the password saved in User column in Database. Need to compare encrypted versions of passwords.
Password and email are mandatory query parameters, need validation before start checking.

If user is valid and password is correct need to generate JWT token. 
So REST endpoint should return valid JWT token for user. 

User this link as reference https://www.codejava.net/frameworks/spring-boot/spring-security-jwt-authentication-tutorial
Pay attention on step 7 that is how to create JWT token for user is password and email are correct. Link describe all steps for JWT login scenario.

**Comment by AngelaM123** [comment]
Implemented login functionality in backend services , made new rest endpoint for its purposes that accepts the required parameters. Checking  if the user is exists and its password . Generating JWT token .Followed the steps in the recommended link in the above comment

**Comment by MarinTrpenovski** [comment]
Code looks good , please fix following note related to styling.
remove commented numbers


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/18595bba-7c6f-4fa0-ab62-d6894653a565)

throw statement in same line as method definition 


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/5c8ce486-d0e9-47f3-95d0-007ab5eb9914)



![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/9b4feff7-3955-4ab2-9ea5-7e72b85b4747)



Check does username and password are ok is good, but return statement is not ok. Read description of the issue. If username  and password are ok, REST endpoint should return JWT Token not message that credentials are valid or not valid. 
In service layer if credentials are not valid should throw Exception("Invalid username or password") and service should return string (JWT Token). 

![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/390622ca-6c5d-49dd-a158-f840d10079fb)


@AngelaM123 Fix following notes so we can close this issue.

**Comment by AngelaM123** [comment]
Applied the required notes , did the styling and applied properly the return of the JWT token

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. Just one note:

What will happened if user with email and password doesn't exist in Database. I can not find code that handle this scenario. I think need to validate does user exist in Database before generate token for user, who might not even exist in Database.

Also please remove commented code in UserDaoImpl class.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/d86d2a72-443f-43b3-8db6-f66bab4958fe)

**Comment by AngelaM123** [comment]
Removed the unused method in the class also wrote code that covers that specific scenario that was emphasized in the above comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good, closing this issue
