### ISSUE TITLE
Implement JWT Authentication in project

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#81]
In Application we have two filters.

One of the filter need to check if each of the requests does have Authorization header and check does JWT Token is valid in header.
If JWT Token in header is valid then allow requests to access on appropriate REST endpoint. Otherwise if JWT is missing in header or is not valid throw an Exception and don't allow the request to access on the appropriate resource. 

Use this link as a reference https://www.javainuse.com/spring/boot-jwt (Here are 2 topics for generating and validate JWT token) For this issue need to understand and implement the validation part.
This link is useful also https://www.baeldung.com/java-jwt-check-expiry-no-exception

This issue is related with #92 , Filter that intercept request which should be authorize need to check first does token exist in header and does token is valid.

**Comment by AngelaM123** [comment]
I have modified AuthenFilter class to handle the JWT token in the Authorization header  of the HTTP request

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good , fix following notes:
1. 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/989d4251-46e3-4efe-9597-30400005e31d)

About code styling apply notes for image. 

2.  Also you have try catch code block , what will happened if error occur during token validation ? Apply appropriate fix in code.
3. what will happened in jwtToken is null ?  you don't handle scenario where jwtToken is null , try to think about edge cases (scenarios) when working on service. Try think in this direction.. if you have IF check in code ... what will happened if IF condition  is not satisfied. By this approach you can predict some edge cases scenarios and prevent some bugs and issues while you develop new features.
4. Remove commented code
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/1c57be91-128f-41e9-bb1e-f36e08dfa0fa)

**Comment by AngelaM123** [comment]
Applied the notes that were required in the above comment including the styling , removing the commented code and changed the try catch block as suggested

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks better. 

Please give your opinion about step 3 from my previous comment.
I don't suggest removing try catch block I asked what will happen if error occur ?

The following notes should be changed : 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/b278a9ae-cb12-42cb-a84f-f8a4bb212729)

First (1) note on image is that what happened when you make filter.doChain() ? Is it ok to make filter.doChain if request doesn't have jwt token in header ? I think we should prevent request to be sent to the REST endpoint , right ?

Second(2) is that doesn't make sense to have == true operator in if condition because method return boolean type right ?
Also same as previous note , what happened when you invoke filter.doChain() method ? Does it make sense to invoke doChain method if jwt is not valid for some reason ?

Test the filter logic via postman, try to cover multiple scenarios.

**Comment by AngelaM123** [comment]
I have removed every chain.doFilter command with leaving the return statement and by this the filter is preventing the requests with invalid or null jwtToken to be send to the appropriate REST endpoint.
Also one idea is to add header in the response of the filter with message of invalid or missing jwtToken so it can be handled in the frontend. Marin, what do you think about this idea? e.g.  httpServletResponse.setHeader("jwtTokenStatus", "messageStatus");

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Did you push the code ? I can not see PR that are ready for merging.

Correct about first stamenet that without chain.doFilter() requests are not sent to the REST endpoint but that is idea, right ? If token is not valid or doesn't; exist in header prevent to be sent to the REST endpoint. (Stop execution of the request).

About second that is good idea, but what you will achieved with that ? you want to set this message in catch block so if error occur to set this as response header ?

**Comment by AngelaM123** [comment]
If a token is missing or is not valid , the request will not be sent to the rest endpoint, but instead we can catch an exception so it can be send to the response and handled by the interceptor in UI
The second idea is:
Instead of exception, a new header to be set in the response with a message of missing or invalid token and then also to be handled by the interceptor in UI

**Comment by MarinTrpenovski** [comment]
@AngelaM123 both explanations are correct. 
About second explanation, you don't need to set response header field. Because interceptor in the UI doesn't check header of the response that is sent from server. Interceptor check payload (data, message properties but as response body ) that is sent.

You are right about try catch explanation. But if error occur you need to create response in catch block where you handle exception. See following code snippet how to handle if error occur while checking JWT in filter.
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/9152c1bc-b9b8-4307-a5bf-55d8e5bfcf2e)


Also one more note, I think this code is not needed in AuthFilter class
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/90eb6914-6347-4c81-8fda-94b1dfda0004)

By this code if request for login come the FIlter then request will not be proceed to the endpoint , right ? 
In web.xml file we define URL for each filter , right. So for Requests that need to be authorized/authenticated we use AuthFilter. We set this filter to intercept this request. For request like /login /signup where user doesn't need to be authenticated then requests are not intercept by the filter. 
So configuration for filters, which filter to be triggered when request come to server we configure in web.xml file 
![image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/c36c0b85-d0b1-4b41-8a3b-c442cb5f2570)

**Comment by AngelaM123** [comment]
Applied the suggested notes from the above comment , made change sin the web.xml file and in the filter configuration , removed unnecessary code

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. Closing this issue.
