### ISSUE TITLE
Create logging mechanism in project

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#87]
For better tracking of errors and exceptions that might be reported by user need to have implementation of logging mechanism. Logger need to keep track in new log files. Log files should be created per day. 

Idea is to have log files that can be saved for any failures (errors) that might happen during execution some of the services.

https://www.geeksforgeeks.org/spring-boot-logging/
https://medium.com/@nutanbhogendrasharma/implement-logger-in-spring-boot-project-part-3-133d869e8bb

Implement logger in each of the classes that exist and add info messages for each of the methods and error messages when some exception occurs. The idea of logger in the application is that for developers will be much more easier to detect if some bug is reported by user or some application error occur during service execution.

**Comment by AngelaM123** [comment]
Implemented logger in each of the classes that exist and add info messages for each of the methods and error messages when some exception occurs

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Logger integration in the project looks good. But I can not see where the logger is implemented in exceptions and classes in the project

**Comment by AngelaM123** [comment]
Tried to implement the required notes from the above comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 I guess that log is working ok because I see that logs folder is created and found log file in the folder. Fix following notes so we can close the issue:


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/21adf5ed-5a22-495b-ac1f-95f512ca3aac)

Note 1 : Remove the logs folder and target folder from future commits.
Note 2,3,4 ... I found 3 same files in 3 different locations. I think only one file is needed , Am I right ? 



I can not find any implementation of logger in the Exception handler methods. 
![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/69b00918-1e2d-43f7-92e9-fb9ee4099678)



Message in the logger is too generic, try to write something more descriptive so it will be easier for developers to detect where error occur. That is idea of logger as much as possible easily to detect the bug/issue/exception in the application.
![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/c812cf4a-29f7-43b9-b72b-84a0e747c25e)

Additionally try to add some info messages in the methods, it can be useful to follow execution of the request so easily can detect errors in the application.

**Comment by AngelaM123** [comment]
Applied all the notes from the above comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good, most of the notes are applied. Does we need 3 XML configuration files for logging ? Can you remove some of then if we don't need it ? Thanks


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/cf621b61-8e5d-4e94-9d9c-37c347c9f39d)

**Comment by AngelaM123** [comment]
Removed two of the xml files

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Its ok now , closing this issue.
