### ISSUE TITLE
Integrate filter in the application

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#9]
Integrate filter in REST endpoints so each of the requests that will come to backend will be intercepted by it and will print URL in the console what is the URL of request. After printing the URL in console leave request to reach the REST endpoint.

@AngelaM123 Please start work on this issue. 

Expected to be done: Monday 06.02.2023.

**Comment by AngelaM123** [comment]
Filter is added in the project

**Comment by MarinTrpenovski** [comment]
Code looks good @AngelaM123 Closing this issue.
