### ISSUE TITLE
Create classes for Authorization support

### ISSUE THREAD

**Issue by MarinTrpenovski** [MarinTrpenovski/Spring-Rest#96]
When database modification is done , in order to support Authorization. Need to implement code in the project in order to support Authorization. 
Create classes for newly created tables in database. This classes will be used to map permissions and roles from Database when need to check user access permissions or perform some actions related with Authorization.

**Comment by AngelaM123** [comment]
Created the model classes for role and permission and all the layers that are required

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good.

Fix following note:


![Image](https://github.com/WORK-MENTOR/Spring-Rest/assets/27773018/add078da-9fd8-4251-a86d-bc8c6efce9e6)

Move constructor to right. 

Additionally in ROLE entity I think need to have LIST of permission property which will be needed to store permissions that are linked to the role when you load them from the database.

**Comment by AngelaM123** [comment]
Applied the required notes from the previous comment

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Code looks good. Closing this issue
